### PR TITLE
[GATE 1768] Java library error handling

### PR DESCRIPTION
**Pull request by dpitch40**
Started version 0.1.1; stopped suppressing 404/non-GET request errors. Corrected/clarified a few unit tests.

### CODE REVIEW

**Comment by nphcbm** [comment]
@dpitch40 any particular reason your changed the test region the unit test?

**Comment by dpitch40** [comment]
It was a workaround to avoid the Bandwidth bug where numbers that show up as available really aren't. NC worked when I first added those unit tests, but didn't as I was testing this branch. I can remove those changes since SC might well not work next time the tests are run.

**Comment by nphcbm** [comment]
@dpitch40 you should have a fall back to try another state.

**Comment by dpitch40** [comment]
@nphcbm There is the same risk that the error would happen with the new state. Should I ultimately try every state in some order? That would be the most robust way to make the tests work without relying on manually changing the region.

**Review by nphcbm — APPROVED** [review]

**Pull request merged**
